### PR TITLE
Implement internal RTTI features

### PR DESCRIPTION
**Pull request by crazyjul**
Implement an simplified RTTI. libRocket can now be built without C++
RTTI enabled while keeping the dynamic cast feature

### CODE REVIEW

**Comment by dwimsey** [comment]
I don't suppose you have any interest in bringing this current?

**Comment by crazyjul** [comment]
I would do it if you have any interest in it. 

We still use librocket, but essentially from our clone. Any feature we can contribute back is essential to us

**Comment by dwimsey** [comment]
I would appreciate it, Its a good patch and cuts down on some code when employed.  I would like to pull it in.

**Comment by crazyjul** [comment]
Aargh, space issues occured during the merge.

**Comment by crazyjul** [comment]
Looks ok now

**Comment by crazyjul** [comment]
Anything missing?

**Pull request closed without merging**
