### PR TITLE
Allow fonts to be uploaded as 8bpp textures to save on video RAM

### PR DESCRIPTION
**Pull request by viciious**
This is a compile-time option, pass preprocessor ROCKET_8BPP_FONTS option to enable 8bpp fonts

### CODE REVIEW

**Comment by dwimsey** [comment]
I like it, but it breaks ABI/API compatibility the way it is now by requiring a new argument, regardless of defining ROCKET_8BPP_FONTS or not

**Comment by dwimsey** [comment]
I'll merge this and fix the ABI/API compat afterwords when I get the chance if you don't want to

**Comment by viciious** [comment]
Yes, I believe its more important to have consistent API regardless of how particular instance of libRocket dynamic library was compiled.

Can't remember if libRocket has any API versioning, does it?

**Comment by dwimsey** [comment]
Can you recreate this pull request (master has been reverted to not include the merge but github doesn't seem to notice)

After applying the patch, the load document sample had all of its text blocky rather than text.


Before
before

After
after

**Pull request merged**
