### PR TITLE
Fix typo which breaks compilation in mingw64

### PR DESCRIPTION
**Pull request by viciious**

### CODE REVIEW

**Comment by dwimsey** [comment]
Very odd, thats not causing an error on my build farm.

**Comment by dwimsey** [comment]
Thanks!

**Comment by viciious** [comment]
Must be some happy coincidence on your side, because on our buildfarm,
mingw64 build fails with the following error:

In file included from Source/Core/../../Include/Rocket/Core/Types.h:44:0,
                 from Source/Core/../../Include/Rocket/Core/Core.h:31,
                 from Source/Core/precompiled.h:31,
                 from Source/Core/Variant.cpp:28:
Source/Core/Variant.cpp: In constructor ‘Rocket::Core::Variant::Variant()’:
Source/Core/Variant.cpp:39:58: error: aggregate
‘Rocket::Core::STATIC_ASSERTION_FAILURE<false>
LOCAL_DATA_TOO_SMALL_FOR_String’ has incomplete type and cannot be
defined
  ROCKET_STATIC_ASSERT(sizeof(String) <= LOCAL_DATA_SIZE,
LOCAL_DATA_TOO_SMALL_FOR_String);
                                                          ^
Source/Core/../../Include/Rocket/Core/Debug.h:106:86: note: in
definition of macro ‘ROCKET_STATIC_ASSERT’
 #define ROCKET_STATIC_ASSERT(cond, msg)
Rocket::Core::STATIC_ASSERTION_FAILURE<cond> msg; (void)&msg

Traced that error back to ROCKET_ARCH_64 being undefined.


2015-01-08 4:25 GMT+03:00 David Wimsey <notifications@github.com>:

> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libRocket/libRocket/pull/236#issuecomment-69122509>.
>



-- 
Best regards,
 Victor Luchitz

**Comment by dwimsey** [comment]
Yea, that's exactly what I'd expect.  I'll have to see what's going on

**Pull request merged**
